server:
  port: 4000

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true

zuul:
  ignoredServices: '*'
  routes:
    pitching-service:
      path: /pitching/**
      serviceId: pitching-service