server:
  port: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: pitching-service