server:
  port: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: pitching-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/exampledb
    username: root
    password: root