spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:1234/testdb?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root