spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://127.0.0.1:1235/pitcher-test-db
    driverClassName: org.postgresql.Driver
    username: root
    password: root