spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/pitcher-test-db
    driverClassName: org.postgresql.Driver
    username: root
    password: root