server:
  port: 3001

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: pitcher-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/pitchers
    username: root
    password: root